# Generated by Django 4.2.7 on 2023-11-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_email_booking_first_name_booking_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='people',
            new_name='number_of_guests',
        ),
    ]
