# Generated by Django 4.2.7 on 2023-11-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_people_booking_number_of_guests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
