# Generated by Django 4.2.7 on 2023-11-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
